export const NESTJS_NOTIFICATIONS_OPTIONS = 'NESTJS_NOTIFICATIONS_OPTIONS';
export const NESTJS_NOTIFICATIONS_QUEUE = 'NESTJS_NOTIFICATIONS_QUEUE';
export const NESTJS_NOTIFICATIONS_JOB_OPTIONS = 'NESTJS_NOTIFICATIONS_JOB_OPTIONS';
